### ISSUE TITLE
Performance Impact ?

### ISSUE THREAD

**Issue by tangorri** [marklagendijk/angular-class#5]
Hi @marklagendijk and thanks that's an interesting project.
Is there an performance impact on using angular-class ?

**Comment by marklagendijk** [comment]
@tangorri thanks! I don't expect it to have a significant performance impact, but I never measured it. I see Angular Class as an useful way of using classes with Ecmascript 5. In the long run Ecmascript 6 / Typescript will win. The benefits they bring are worth the extra overhead of having to transpile.
